lsb_8bit_data_test	2  	+UVM_TESTNAME=lsb_8bit_data_test +RX_NEG=0 +TX_NEG=1 +CHAR_LEN=8 +CHAR_LEN=16 +CHAR_LEN=32 +CHAR_LEN=64 +CHAR_LEN=127 +CHAR_LEN=0 
lsb_8bit_data_test	2  	+UVM_TESTNAME=lsb_8bit_data_test +MSB_1ST +RX_NEG=0 +TX_NEG=1 +CHAR_LEN=8 +CHAR_LEN=16 +CHAR_LEN=32 +CHAR_LEN=64 +CHAR_LEN=127 +CHAR_LEN=0
lsb_8bit_data_test	3  	+UVM_TESTNAME=lsb_8bit_data_test +MSB_1ST 
w_r_test 		1 	+UVM_TESTNAME=w_r_test
size_test 		1 	+UVM_TESTNAME=size_test
size1_test 		1 	+UVM_TESTNAME=size1_test
sanity_test 		1 	+UVM_TESTNAME=sanity_test
